/*
 * yiqi_tools_factory_generator.cpp
 *
 * Tool used to parse an input tools_factory.cpp.in and
 * generate output tools_factory.cpp
 */

#include <cstring>
#include <functional>
#include <locale>
#include <sstream>
#include <string>
#include <vector>

#include "generators_common.h"

namespace yg = yiqi::generators;
namespace ygu = yiqi::generators::util;
namespace ygt = yiqi::generators::transformations;

namespace
{
    void InsertHeader (std::string &str)
    {
        char const *header = "/*\n"
                             " * tools_factory.cpp\n"
                             " *\n"
                             " * This file was autogenerated from\n"
                             " * tools_factory.cpp.in. It contains some code\n"
                             " * to bootstrap all of the available tools to\n"
                             " * yiqi at the time this build was compiled.\n"
                             " * Do not edit this file.\n"
                             " *\n"
                             " * See LICENCE.md for Copyright information.\n"
                             " */\n";

        str.insert (0, header);
    }

    void GenerateInstrumentationToolsArray (std::string             &string,
                                            ygu::StringVector const &tools)
    {
        std::string const searchToken ("INSTRUMENTATION_TOOL_STRING_NAMES_DEF");
        static char const *header = " { InstrumentationTool::";
        static size_t const headerSize = std::strlen (header);

        auto transformation =
            [&](std::string const &str, size_t i, size_t n) -> std::string {
                std::stringstream ss;

                ss << header << str << ", " << "\"" << str << "\"" << " }";

                if (i < n)
                    ss << ",";

                std::string modified (ss.str ());
                modified[headerSize] = std::toupper (modified[headerSize]);
                return modified;
            };

        ygu::GenerateFromTools (string,
                                searchToken,
                                transformation,
                                tools);
    }

    void GenerateFactoryPackagesArray (std::string             &string,
                                       ygu::StringVector const &tools)
    {
        std::string const token ("INSTRUMENTATION_TOOLS_FACTORY_PACKAGES");
        static char const *header = " { yitp::Make";
        static size_t const headerSize = std::strlen (header);

        static char const *secondHeader = ", yitc::Make";
        static size_t const secondHeaderSize = std::strlen (secondHeader);

        auto transformation =
            [&](std::string const &str, size_t i, size_t n) -> std::string {
                std::stringstream ss;

                ss << header << str << secondHeader << str << " }";

                if (i < n)
                    ss << ",";

                std::string modified (ss.str ());
                modified[headerSize] = std::toupper (modified[headerSize]);

                size_t const offset = headerSize +
                                      str.size () +
                                      secondHeaderSize;

                modified[offset] = std::toupper (modified[offset]);
                return modified;
            };

            ygu::GenerateFromTools (string,
                                    token,
                                    transformation,
                                    tools);
    }
}

int main (int argc, char **argv)
{
    std::string inputFileName, outputFileName;
    std::vector <std::string> tools;

    try
    {
        using namespace std::placeholders;

        yg::GetOptions (argc,
                        argv,
                        inputFileName,
                        outputFileName,
                        tools);

        std::string inputFileData (yg::ReadInputFile (inputFileName));
        yg::ApplyTransformations (inputFileData,
                                  ygt::DeleteComments,
                                  ygt::RemoveLineIfEndingWithDEL,
                                  InsertHeader,
                                  std::bind (GenerateInstrumentationToolsArray,
                                               _1, std::ref (tools)),
                                  std::bind (GenerateFactoryPackagesArray,
                                              _1, std::ref (tools)),
                                  std::bind (ygt::GenerateInstrumentationToolsN,
                                               _1, tools.size ()),
                                  ygt::CompressNewlines);
        yg::WriteToOutputFile (outputFileName,
                               inputFileData);

    }
    catch (std::exception const &e)
    {
        std::cerr << e.what () << std::endl;
        return 1;
    }
    catch (...)
    {
        std::cerr << "Unknown error occurred";
        return 1;
    }

    return 0;
}